version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/home/app
    command: >
      sh -c "npm install && npm run serve"
    container_name: STEEM-LOGIN
